### PR TITLE
Moving to more flexible catalog [WIP]

### PR DESCRIPTION
**Pull request by geramirez**
The current broker only supports one service type, this PR moves to a catalog that supports multiple services. 
Changes:
- Catalog is built from `catalog.yaml` file
- Catalog is now a struct that persists in memory and passed around as a pointer.
- Internal database now stores the service id (we'll need to set the default in the migrations to the current service id)
- gutted the `Godep/_workspace/` directory
- using the new version of the [golang aws sdk](https://aws.amazon.com/releasenotes/0023860075558122) and the new version of [gorm](https://github.com/jinzhu/gorm) both which caused syntax changes.

### CODE REVIEW

**Comment by jcscottiii** [comment]
You have `DbType` in there. you'll want to remove this from the generic `Plan` and maybe put it in a `DBPlan` which inherits the generic Plan.
``` go
type Plan struct {
	Id           string       `yaml:"id" json:"id"`
	Name         string       `yaml:"name" json:"name"`
	Description  string       `yaml:"description" json:"description"`
	Metadata     PlanMetadata `yaml:"metadata" json:"metadata"`
	Free         bool         `yaml:"free" json:"free"`
	Adapter      string       `yaml:"adapter" json:"-"`
	InstanceType string       `yaml:"instanceType" json:"-"`
	DbType       string       `yaml:"dbType" json:"-"`
}
```

**Comment by jcscottiii** [comment]
what would be nice would be to use this: https://github.com/cloudfoundry/cli/blob/8450d0f4264a1b6194ea89aa162fea1f6980d5ee/cf/models/service_plan.go but i think it's impossible to add tags to struct from the outside.

**Comment by djvdorp** [comment]
Since #14 just got merged, can we close this one @geramirez @jcscottiii ?

**Comment by geramirez** [comment]
@djvdorp yep, closing it now.

**Pull request closed without merging**
